# -*- coding: utf-8 -*-
"""lv3_finalProject_Muhammad_DECI4-S-418111(Preparing Part).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRfso2G7BPOv_pj3IghFMevSf6ZJQA1M
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup as BS
import requests as rs

#Collecting Data from GitHub API & Converting the Data into a DataFrame
URL = "https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"
response = rs.get(URL)
data = response.json()
Adf = pd.DataFrame(data["items"])
#Selecting the Required Columns
df=Adf[[
"name",
"owner",
"language",
"stargazers_count",
"forks_count",
"watchers_count",
"open_issues_count",
"created_at",
"updated_at",
"license"
]]

"""#**From Here,Cleaning & Exploring the Data started...**
During Prepration, the following will be performed:


Extracting the warehouse owner's username from the Owner column.

Extracting the license name from the License column.

Resolving missing values.

Deleting duplicate records.

Converting the creation date and update date to DateTime.

Renaming columns for easier use in SQL.

Formating and organizing text.

"""

df.columns = df.columns.str.lower().str.strip()
print("Final DataFrame Shape:", df.shape)

df.head()

df["created_at"]=pd.to_datetime(df["created_at"])
df["updated_at"]=pd.to_datetime(df["updated_at"])
owner_names = pd.DataFrame([item["owner"]["login"] for item in data["items"] if isinstance(item.get("owner"), dict)], columns=["username"])

license_names = pd.DataFrame([item["license"]["name"] for item in data["items"] if isinstance(item.get("license"), dict)], columns=["license_name"])

resdf = pd.concat([owner_names, license_names], axis=1)
df["owner"]=resdf["username"]
df["license"]=resdf["license_name"]

df = df.drop_duplicates()

df.shape

df.head()

df.isnull().sum()

df=df.dropna()

df.shape

df.info()

df.describe()

numeric_df = df.select_dtypes(include='number')
gap = numeric_df.max() - numeric_df.min()
print(gap)

df=df.rename(columns={"stargazers_count"	: "stargazers" ,"forks_count"	: "forks" ,"watchers_count"	: "watchers" ,"open_issues_count" : "open_issues","created_at" : "creation","updated_at" : "updating" })

df['name'] = df['name'].str.lower().str.strip()
df['owner'] = df['owner'].str.lower().str.strip()
df['language'] = df['language'].str.strip()
df['license'] = df['license'].str.lower().str.strip()

'''When I Explored the head of the Data,I found that someone Entired Jupyter Notebook
 (a platform usually used for Python Coding);so I fixed that.'''
df.groupby(by="language").size()

df['language'] = df['language'].replace('Jupyter Notebook', 'Python')

df.groupby(by="language").size()

df.head()

#Saving the Cleaned Data
df.to_csv("github_projects.csv",index=False)

